/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SDGameGetResponseFeesInner model module.
 * @module model/SDGameGetResponseFeesInner
 * @version 0.0.3
 */
class SDGameGetResponseFeesInner {
    /**
     * Constructs a new <code>SDGameGetResponseFeesInner</code>.
     * @alias module:model/SDGameGetResponseFeesInner
     */
    constructor() { 
        
        SDGameGetResponseFeesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SDGameGetResponseFeesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SDGameGetResponseFeesInner} obj Optional instance to populate.
     * @return {module:model/SDGameGetResponseFeesInner} The populated <code>SDGameGetResponseFeesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SDGameGetResponseFeesInner();

            if (data.hasOwnProperty('feePercentage')) {
                obj['feePercentage'] = ApiClient.convertToType(data['feePercentage'], 'Number');
            }
            if (data.hasOwnProperty('feeType')) {
                obj['feeType'] = ApiClient.convertToType(data['feeType'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SDGameGetResponseFeesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SDGameGetResponseFeesInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['feeType'] && !(typeof data['feeType'] === 'string' || data['feeType'] instanceof String)) {
            throw new Error("Expected the field `feeType` to be a primitive type in the JSON string but got " + data['feeType']);
        }

        return true;
    }


}



/**
 * The integer value of feePercentage. 
 * @member {Number} feePercentage
 */
SDGameGetResponseFeesInner.prototype['feePercentage'] = undefined;

/**
 * The type of fee
 * @member {String} feeType
 */
SDGameGetResponseFeesInner.prototype['feeType'] = undefined;






export default SDGameGetResponseFeesInner;

