/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SDOrderGetAllResponseTokensRequestedInner model module.
 * @module model/SDOrderGetAllResponseTokensRequestedInner
 * @version 0.0.3
 */
class SDOrderGetAllResponseTokensRequestedInner {
    /**
     * Constructs a new <code>SDOrderGetAllResponseTokensRequestedInner</code>.
     * @alias module:model/SDOrderGetAllResponseTokensRequestedInner
     * @param tokenId {Number} Token ID Number (unsigned 32 bit integer)
     * @param amount {Number} Token ID Number (unsigned 32 bit integer)
     */
    constructor(tokenId, amount) { 
        
        SDOrderGetAllResponseTokensRequestedInner.initialize(this, tokenId, amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tokenId, amount) { 
        obj['tokenId'] = tokenId;
        obj['amount'] = amount;
    }

    /**
     * Constructs a <code>SDOrderGetAllResponseTokensRequestedInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SDOrderGetAllResponseTokensRequestedInner} obj Optional instance to populate.
     * @return {module:model/SDOrderGetAllResponseTokensRequestedInner} The populated <code>SDOrderGetAllResponseTokensRequestedInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SDOrderGetAllResponseTokensRequestedInner();

            if (data.hasOwnProperty('tokenId')) {
                obj['tokenId'] = ApiClient.convertToType(data['tokenId'], 'Number');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SDOrderGetAllResponseTokensRequestedInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SDOrderGetAllResponseTokensRequestedInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SDOrderGetAllResponseTokensRequestedInner.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

SDOrderGetAllResponseTokensRequestedInner.RequiredProperties = ["tokenId", "amount"];

/**
 * Token ID Number (unsigned 32 bit integer)
 * @member {Number} tokenId
 */
SDOrderGetAllResponseTokensRequestedInner.prototype['tokenId'] = undefined;

/**
 * Token ID Number (unsigned 32 bit integer)
 * @member {Number} amount
 */
SDOrderGetAllResponseTokensRequestedInner.prototype['amount'] = undefined;






export default SDOrderGetAllResponseTokensRequestedInner;

