/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SDPlayerWalletGetResponseWalletInnerMoniesInner from './SDPlayerWalletGetResponseWalletInnerMoniesInner';

/**
 * The SDPlayerWalletGetResponseWalletInner model module.
 * @module model/SDPlayerWalletGetResponseWalletInner
 * @version 0.0.3
 */
class SDPlayerWalletGetResponseWalletInner {
    /**
     * Constructs a new <code>SDPlayerWalletGetResponseWalletInner</code>.
     * @alias module:model/SDPlayerWalletGetResponseWalletInner
     * @param blockchain {String} The name of the blockchain
     * @param address {String} The players blockchain Address
     */
    constructor(blockchain, address) { 
        
        SDPlayerWalletGetResponseWalletInner.initialize(this, blockchain, address);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, blockchain, address) { 
        obj['blockchain'] = blockchain;
        obj['address'] = address;
    }

    /**
     * Constructs a <code>SDPlayerWalletGetResponseWalletInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SDPlayerWalletGetResponseWalletInner} obj Optional instance to populate.
     * @return {module:model/SDPlayerWalletGetResponseWalletInner} The populated <code>SDPlayerWalletGetResponseWalletInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SDPlayerWalletGetResponseWalletInner();

            if (data.hasOwnProperty('blockchain')) {
                obj['blockchain'] = ApiClient.convertToType(data['blockchain'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('monies')) {
                obj['monies'] = ApiClient.convertToType(data['monies'], [SDPlayerWalletGetResponseWalletInnerMoniesInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SDPlayerWalletGetResponseWalletInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SDPlayerWalletGetResponseWalletInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SDPlayerWalletGetResponseWalletInner.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['blockchain'] && !(typeof data['blockchain'] === 'string' || data['blockchain'] instanceof String)) {
            throw new Error("Expected the field `blockchain` to be a primitive type in the JSON string but got " + data['blockchain']);
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }
        if (data['monies']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['monies'])) {
                throw new Error("Expected the field `monies` to be an array in the JSON data but got " + data['monies']);
            }
            // validate the optional field `monies` (array)
            for (const item of data['monies']) {
                SDPlayerWalletGetResponseWalletInnerMoniesInner.validateJSON(item);
            };
        }

        return true;
    }


}

SDPlayerWalletGetResponseWalletInner.RequiredProperties = ["blockchain", "address"];

/**
 * The name of the blockchain
 * @member {String} blockchain
 */
SDPlayerWalletGetResponseWalletInner.prototype['blockchain'] = undefined;

/**
 * The players blockchain Address
 * @member {String} address
 */
SDPlayerWalletGetResponseWalletInner.prototype['address'] = undefined;

/**
 * An array of the players balances on a given blockchain
 * @member {Array.<module:model/SDPlayerWalletGetResponseWalletInnerMoniesInner>} monies
 */
SDPlayerWalletGetResponseWalletInner.prototype['monies'] = undefined;






export default SDPlayerWalletGetResponseWalletInner;

