/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SDPlayerWalletGetResponseWalletInnerMoniesInner model module.
 * @module model/SDPlayerWalletGetResponseWalletInnerMoniesInner
 * @version 0.0.3
 */
class SDPlayerWalletGetResponseWalletInnerMoniesInner {
    /**
     * Constructs a new <code>SDPlayerWalletGetResponseWalletInnerMoniesInner</code>.
     * The Money object representation of the balance
     * @alias module:model/SDPlayerWalletGetResponseWalletInnerMoniesInner
     */
    constructor() { 
        
        SDPlayerWalletGetResponseWalletInnerMoniesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SDPlayerWalletGetResponseWalletInnerMoniesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SDPlayerWalletGetResponseWalletInnerMoniesInner} obj Optional instance to populate.
     * @return {module:model/SDPlayerWalletGetResponseWalletInnerMoniesInner} The populated <code>SDPlayerWalletGetResponseWalletInnerMoniesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SDPlayerWalletGetResponseWalletInnerMoniesInner();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SDPlayerWalletGetResponseWalletInnerMoniesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SDPlayerWalletGetResponseWalletInnerMoniesInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['amount'] && !(typeof data['amount'] === 'string' || data['amount'] instanceof String)) {
            throw new Error("Expected the field `amount` to be a primitive type in the JSON string but got " + data['amount']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }

        return true;
    }


}



/**
 * The balance in minor units. ex: 2000000 for 2 coins USDC
 * @member {String} amount
 */
SDPlayerWalletGetResponseWalletInnerMoniesInner.prototype['amount'] = undefined;

/**
 * The currency code associated with the amount. ex: 'USDC'
 * @member {String} currency
 */
SDPlayerWalletGetResponseWalletInnerMoniesInner.prototype['currency'] = undefined;






export default SDPlayerWalletGetResponseWalletInnerMoniesInner;

