/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SDPlayerGetAllResponse model module.
 * @module model/SDPlayerGetAllResponse
 * @version 0.0.3
 */
class SDPlayerGetAllResponse {
    /**
     * Constructs a new <code>SDPlayerGetAllResponse</code>.
     * This is the data output json model
     * @alias module:model/SDPlayerGetAllResponse
     * @extends Object
     * @param playerId {String} Player ID in the form of a UUID
     * @param uniqueId {String} Game player's unique ID from the game itself
     */
    constructor(playerId, uniqueId) { 
        
        SDPlayerGetAllResponse.initialize(this, playerId, uniqueId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, playerId, uniqueId) { 
        obj['playerId'] = playerId;
        obj['uniqueId'] = uniqueId;
    }

    /**
     * Constructs a <code>SDPlayerGetAllResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SDPlayerGetAllResponse} obj Optional instance to populate.
     * @return {module:model/SDPlayerGetAllResponse} The populated <code>SDPlayerGetAllResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SDPlayerGetAllResponse();

            ApiClient.constructFromObject(data, obj, 'String');
            

            if (data.hasOwnProperty('playerId')) {
                obj['playerId'] = ApiClient.convertToType(data['playerId'], 'String');
            }
            if (data.hasOwnProperty('uniqueId')) {
                obj['uniqueId'] = ApiClient.convertToType(data['uniqueId'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('lastSeen')) {
                obj['lastSeen'] = ApiClient.convertToType(data['lastSeen'], 'String');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SDPlayerGetAllResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SDPlayerGetAllResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SDPlayerGetAllResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['playerId'] && !(typeof data['playerId'] === 'string' || data['playerId'] instanceof String)) {
            throw new Error("Expected the field `playerId` to be a primitive type in the JSON string but got " + data['playerId']);
        }
        // ensure the json data is a string
        if (data['uniqueId'] && !(typeof data['uniqueId'] === 'string' || data['uniqueId'] instanceof String)) {
            throw new Error("Expected the field `uniqueId` to be a primitive type in the JSON string but got " + data['uniqueId']);
        }
        // ensure the json data is a string
        if (data['lastSeen'] && !(typeof data['lastSeen'] === 'string' || data['lastSeen'] instanceof String)) {
            throw new Error("Expected the field `lastSeen` to be a primitive type in the JSON string but got " + data['lastSeen']);
        }
        // ensure the json data is a string
        if (data['image'] && !(typeof data['image'] === 'string' || data['image'] instanceof String)) {
            throw new Error("Expected the field `image` to be a primitive type in the JSON string but got " + data['image']);
        }

        return true;
    }


}

SDPlayerGetAllResponse.RequiredProperties = ["playerId", "uniqueId"];

/**
 * Player ID in the form of a UUID
 * @member {String} playerId
 */
SDPlayerGetAllResponse.prototype['playerId'] = undefined;

/**
 * Game player's unique ID from the game itself
 * @member {String} uniqueId
 */
SDPlayerGetAllResponse.prototype['uniqueId'] = undefined;

/**
 * Game player's ID in the database
 * @member {Number} id
 */
SDPlayerGetAllResponse.prototype['id'] = undefined;

/**
 * Date and time the player was 'last seen' actively participating in the game
 * @member {String} lastSeen
 */
SDPlayerGetAllResponse.prototype['lastSeen'] = undefined;

/**
 * URL of image cached by Stardust
 * @member {String} image
 */
SDPlayerGetAllResponse.prototype['image'] = undefined;






export default SDPlayerGetAllResponse;

