/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SDPlayerGetResponse model module.
 * @module model/SDPlayerGetResponse
 * @version 0.0.3
 */
class SDPlayerGetResponse {
    /**
     * Constructs a new <code>SDPlayerGetResponse</code>.
     * This is the data output json model
     * @alias module:model/SDPlayerGetResponse
     * @extends Object
     * @param playerId {String} Player ID in the form of a UUID
     * @param uniqueId {String} Player ID in the form of a the game owner's internal playerId, i.e. email address
     */
    constructor(playerId, uniqueId) { 
        
        SDPlayerGetResponse.initialize(this, playerId, uniqueId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, playerId, uniqueId) { 
        obj['playerId'] = playerId;
        obj['uniqueId'] = uniqueId;
    }

    /**
     * Constructs a <code>SDPlayerGetResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SDPlayerGetResponse} obj Optional instance to populate.
     * @return {module:model/SDPlayerGetResponse} The populated <code>SDPlayerGetResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SDPlayerGetResponse();

            ApiClient.constructFromObject(data, obj, 'String');
            

            if (data.hasOwnProperty('playerId')) {
                obj['playerId'] = ApiClient.convertToType(data['playerId'], 'String');
            }
            if (data.hasOwnProperty('uniqueId')) {
                obj['uniqueId'] = ApiClient.convertToType(data['uniqueId'], 'String');
            }
            if (data.hasOwnProperty('lastSeen')) {
                obj['lastSeen'] = ApiClient.convertToType(data['lastSeen'], 'String');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SDPlayerGetResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SDPlayerGetResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SDPlayerGetResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['playerId'] && !(typeof data['playerId'] === 'string' || data['playerId'] instanceof String)) {
            throw new Error("Expected the field `playerId` to be a primitive type in the JSON string but got " + data['playerId']);
        }
        // ensure the json data is a string
        if (data['uniqueId'] && !(typeof data['uniqueId'] === 'string' || data['uniqueId'] instanceof String)) {
            throw new Error("Expected the field `uniqueId` to be a primitive type in the JSON string but got " + data['uniqueId']);
        }
        // ensure the json data is a string
        if (data['lastSeen'] && !(typeof data['lastSeen'] === 'string' || data['lastSeen'] instanceof String)) {
            throw new Error("Expected the field `lastSeen` to be a primitive type in the JSON string but got " + data['lastSeen']);
        }
        // ensure the json data is a string
        if (data['image'] && !(typeof data['image'] === 'string' || data['image'] instanceof String)) {
            throw new Error("Expected the field `image` to be a primitive type in the JSON string but got " + data['image']);
        }

        return true;
    }


}

SDPlayerGetResponse.RequiredProperties = ["playerId", "uniqueId"];

/**
 * Player ID in the form of a UUID
 * @member {String} playerId
 */
SDPlayerGetResponse.prototype['playerId'] = undefined;

/**
 * Player ID in the form of a the game owner's internal playerId, i.e. email address
 * @member {String} uniqueId
 */
SDPlayerGetResponse.prototype['uniqueId'] = undefined;

/**
 * Date and time the player was 'last seen' actively participating in the game
 * @member {String} lastSeen
 */
SDPlayerGetResponse.prototype['lastSeen'] = undefined;

/**
 * URL of image cached by Stardust
 * @member {String} image
 */
SDPlayerGetResponse.prototype['image'] = undefined;






export default SDPlayerGetResponse;

