/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SDPlayerMutateRequest model module.
 * @module model/SDPlayerMutateRequest
 * @version 0.0.3
 */
class SDPlayerMutateRequest {
    /**
     * Constructs a new <code>SDPlayerMutateRequest</code>.
     * @alias module:model/SDPlayerMutateRequest
     * @param playerId {String} Can be found with Player/getId(s).
     * @param props {Object} Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7})
     */
    constructor(playerId, props) { 
        
        SDPlayerMutateRequest.initialize(this, playerId, props);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, playerId, props) { 
        obj['playerId'] = playerId;
        obj['props'] = props;
    }

    /**
     * Constructs a <code>SDPlayerMutateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SDPlayerMutateRequest} obj Optional instance to populate.
     * @return {module:model/SDPlayerMutateRequest} The populated <code>SDPlayerMutateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SDPlayerMutateRequest();

            if (data.hasOwnProperty('playerId')) {
                obj['playerId'] = ApiClient.convertToType(data['playerId'], 'String');
            }
            if (data.hasOwnProperty('props')) {
                obj['props'] = ApiClient.convertToType(data['props'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SDPlayerMutateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SDPlayerMutateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SDPlayerMutateRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['playerId'] && !(typeof data['playerId'] === 'string' || data['playerId'] instanceof String)) {
            throw new Error("Expected the field `playerId` to be a primitive type in the JSON string but got " + data['playerId']);
        }

        return true;
    }


}

SDPlayerMutateRequest.RequiredProperties = ["playerId", "props"];

/**
 * Can be found with Player/getId(s).
 * @member {String} playerId
 */
SDPlayerMutateRequest.prototype['playerId'] = undefined;

/**
 * Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7})
 * @member {Object} props
 */
SDPlayerMutateRequest.prototype['props'] = undefined;






export default SDPlayerMutateRequest;

