/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SDPlayerWalletGetResponseWalletInner from './SDPlayerWalletGetResponseWalletInner';

/**
 * The SDPlayerWalletGetResponse model module.
 * @module model/SDPlayerWalletGetResponse
 * @version 0.0.3
 */
class SDPlayerWalletGetResponse {
    /**
     * Constructs a new <code>SDPlayerWalletGetResponse</code>.
     * This is the data output json model
     * @alias module:model/SDPlayerWalletGetResponse
     * @param wallet {Array.<module:model/SDPlayerWalletGetResponseWalletInner>} An array of player wallets on the blockchain
     */
    constructor(wallet) { 
        
        SDPlayerWalletGetResponse.initialize(this, wallet);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, wallet) { 
        obj['wallet'] = wallet;
    }

    /**
     * Constructs a <code>SDPlayerWalletGetResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SDPlayerWalletGetResponse} obj Optional instance to populate.
     * @return {module:model/SDPlayerWalletGetResponse} The populated <code>SDPlayerWalletGetResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SDPlayerWalletGetResponse();

            if (data.hasOwnProperty('wallet')) {
                obj['wallet'] = ApiClient.convertToType(data['wallet'], [SDPlayerWalletGetResponseWalletInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SDPlayerWalletGetResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SDPlayerWalletGetResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SDPlayerWalletGetResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['wallet']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['wallet'])) {
                throw new Error("Expected the field `wallet` to be an array in the JSON data but got " + data['wallet']);
            }
            // validate the optional field `wallet` (array)
            for (const item of data['wallet']) {
                SDPlayerWalletGetResponseWalletInner.validateJSON(item);
            };
        }

        return true;
    }


}

SDPlayerWalletGetResponse.RequiredProperties = ["wallet"];

/**
 * An array of player wallets on the blockchain
 * @member {Array.<module:model/SDPlayerWalletGetResponseWalletInner>} wallet
 */
SDPlayerWalletGetResponse.prototype['wallet'] = undefined;






export default SDPlayerWalletGetResponse;

