/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SDTemplateCountResponse model module.
 * @module model/SDTemplateCountResponse
 * @version 0.0.3
 */
class SDTemplateCountResponse {
    /**
     * Constructs a new <code>SDTemplateCountResponse</code>.
     * @alias module:model/SDTemplateCountResponse
     * @param count {Number} Game ID Number (unsigned 32 bit integer)
     */
    constructor(count) { 
        
        SDTemplateCountResponse.initialize(this, count);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, count) { 
        obj['count'] = count;
    }

    /**
     * Constructs a <code>SDTemplateCountResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SDTemplateCountResponse} obj Optional instance to populate.
     * @return {module:model/SDTemplateCountResponse} The populated <code>SDTemplateCountResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SDTemplateCountResponse();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SDTemplateCountResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SDTemplateCountResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SDTemplateCountResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

SDTemplateCountResponse.RequiredProperties = ["count"];

/**
 * Game ID Number (unsigned 32 bit integer)
 * @member {Number} count
 */
SDTemplateCountResponse.prototype['count'] = undefined;






export default SDTemplateCountResponse;

