/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SDTemplateMutateRequest model module.
 * @module model/SDTemplateMutateRequest
 * @version 0.0.3
 */
class SDTemplateMutateRequest {
    /**
     * Constructs a new <code>SDTemplateMutateRequest</code>.
     * @alias module:model/SDTemplateMutateRequest
     * @param templateId {Number} This is the templateId returned from template/create (ex. 5)
     */
    constructor(templateId) { 
        
        SDTemplateMutateRequest.initialize(this, templateId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, templateId) { 
        obj['templateId'] = templateId;
    }

    /**
     * Constructs a <code>SDTemplateMutateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SDTemplateMutateRequest} obj Optional instance to populate.
     * @return {module:model/SDTemplateMutateRequest} The populated <code>SDTemplateMutateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SDTemplateMutateRequest();

            if (data.hasOwnProperty('templateId')) {
                obj['templateId'] = ApiClient.convertToType(data['templateId'], 'Number');
            }
            if (data.hasOwnProperty('props')) {
                obj['props'] = ApiClient.convertToType(data['props'], Object);
            }
            if (data.hasOwnProperty('publicContractMetadata')) {
                obj['publicContractMetadata'] = ApiClient.convertToType(data['publicContractMetadata'], Object);
            }
            if (data.hasOwnProperty('publicTokenMetadata')) {
                obj['publicTokenMetadata'] = ApiClient.convertToType(data['publicTokenMetadata'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SDTemplateMutateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SDTemplateMutateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SDTemplateMutateRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

SDTemplateMutateRequest.RequiredProperties = ["templateId"];

/**
 * This is the templateId returned from template/create (ex. 5)
 * @member {Number} templateId
 */
SDTemplateMutateRequest.prototype['templateId'] = undefined;

/**
 * Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7})
 * @member {Object} props
 */
SDTemplateMutateRequest.prototype['props'] = undefined;

/**
 * Returned to marketplaces as contract metadata
 * @member {Object} publicContractMetadata
 */
SDTemplateMutateRequest.prototype['publicContractMetadata'] = undefined;

/**
 * Inherited by tokens, and returned to marketplaces as token metadata
 * @member {Object} publicTokenMetadata
 */
SDTemplateMutateRequest.prototype['publicTokenMetadata'] = undefined;






export default SDTemplateMutateRequest;

