/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SDTemplateCreateRequestProps from './SDTemplateCreateRequestProps';

/**
 * The SDTemplateCreateRequest model module.
 * @module model/SDTemplateCreateRequest
 * @version 0.0.3
 */
class SDTemplateCreateRequest {
    /**
     * Constructs a new <code>SDTemplateCreateRequest</code>.
     * @alias module:model/SDTemplateCreateRequest
     * @param name {String} The name of the template (ex. Bronze Axe)
     * @param cap {String} u96 Number as String (ex. 200000000) 
     * @param type {module:model/SDTemplateCreateRequest.TypeEnum} FT is a currency where every instance is the same, NFT is where every token instance differes (ex. FT)
     * @param props {module:model/SDTemplateCreateRequestProps} 
     */
    constructor(name, cap, type, props) { 
        
        SDTemplateCreateRequest.initialize(this, name, cap, type, props);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, cap, type, props) { 
        obj['name'] = name;
        obj['cap'] = cap;
        obj['type'] = type;
        obj['props'] = props;
    }

    /**
     * Constructs a <code>SDTemplateCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SDTemplateCreateRequest} obj Optional instance to populate.
     * @return {module:model/SDTemplateCreateRequest} The populated <code>SDTemplateCreateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SDTemplateCreateRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('cap')) {
                obj['cap'] = ApiClient.convertToType(data['cap'], 'String');
            }
            if (data.hasOwnProperty('contractType')) {
                obj['contractType'] = ApiClient.convertToType(data['contractType'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('ownerAddress')) {
                obj['ownerAddress'] = ApiClient.convertToType(data['ownerAddress'], 'String');
            }
            if (data.hasOwnProperty('props')) {
                obj['props'] = SDTemplateCreateRequestProps.constructFromObject(data['props']);
            }
            if (data.hasOwnProperty('publicContractMetadata')) {
                obj['publicContractMetadata'] = ApiClient.convertToType(data['publicContractMetadata'], Object);
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SDTemplateCreateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SDTemplateCreateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SDTemplateCreateRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['cap'] && !(typeof data['cap'] === 'string' || data['cap'] instanceof String)) {
            throw new Error("Expected the field `cap` to be a primitive type in the JSON string but got " + data['cap']);
        }
        // ensure the json data is a string
        if (data['contractType'] && !(typeof data['contractType'] === 'string' || data['contractType'] instanceof String)) {
            throw new Error("Expected the field `contractType` to be a primitive type in the JSON string but got " + data['contractType']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['ownerAddress'] && !(typeof data['ownerAddress'] === 'string' || data['ownerAddress'] instanceof String)) {
            throw new Error("Expected the field `ownerAddress` to be a primitive type in the JSON string but got " + data['ownerAddress']);
        }
        // validate the optional field `props`
        if (data['props']) { // data not null
          SDTemplateCreateRequestProps.validateJSON(data['props']);
        }
        // ensure the json data is a string
        if (data['symbol'] && !(typeof data['symbol'] === 'string' || data['symbol'] instanceof String)) {
            throw new Error("Expected the field `symbol` to be a primitive type in the JSON string but got " + data['symbol']);
        }

        return true;
    }


}

SDTemplateCreateRequest.RequiredProperties = ["name", "cap", "type", "props"];

/**
 * The name of the template (ex. Bronze Axe)
 * @member {String} name
 */
SDTemplateCreateRequest.prototype['name'] = undefined;

/**
 * u96 Number as String (ex. 200000000) 
 * @member {String} cap
 */
SDTemplateCreateRequest.prototype['cap'] = undefined;

/**
 * The type of custom contract to use for this template. Default will use a shared contract.
 * @member {module:model/SDTemplateCreateRequest.ContractTypeEnum} contractType
 */
SDTemplateCreateRequest.prototype['contractType'] = undefined;

/**
 * FT is a currency where every instance is the same, NFT is where every token instance differes (ex. FT)
 * @member {module:model/SDTemplateCreateRequest.TypeEnum} type
 */
SDTemplateCreateRequest.prototype['type'] = undefined;

/**
 * Blockchain address to set as owner of the custom contract. Required if contractType is set.
 * @member {String} ownerAddress
 */
SDTemplateCreateRequest.prototype['ownerAddress'] = undefined;

/**
 * @member {module:model/SDTemplateCreateRequestProps} props
 */
SDTemplateCreateRequest.prototype['props'] = undefined;

/**
 * Returned to marketplaces as contract metadata
 * @member {Object} publicContractMetadata
 */
SDTemplateCreateRequest.prototype['publicContractMetadata'] = undefined;

/**
 * For ERC20 contracts, this is the ticker symbol
 * @member {String} symbol
 */
SDTemplateCreateRequest.prototype['symbol'] = undefined;





/**
 * Allowed values for the <code>contractType</code> property.
 * @enum {String}
 * @readonly
 */
SDTemplateCreateRequest['ContractTypeEnum'] = {

    /**
     * value: "internal-mint"
     * @const
     */
    "internal-mint": "internal-mint",

    /**
     * value: "ERC721"
     * @const
     */
    "ERC721": "ERC721",

    /**
     * value: "ERC20"
     * @const
     */
    "ERC20": "ERC20"
};


/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
SDTemplateCreateRequest['TypeEnum'] = {

    /**
     * value: "FT"
     * @const
     */
    "FT": "FT",

    /**
     * value: "NFT"
     * @const
     */
    "NFT": "NFT"
};



export default SDTemplateCreateRequest;

