/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SDTokenMintBulkTokenObjectProps model module.
 * @module model/SDTokenMintBulkTokenObjectProps
 * @version 0.0.3
 */
class SDTokenMintBulkTokenObjectProps {
    /**
     * Constructs a new <code>SDTokenMintBulkTokenObjectProps</code>.
     * Internal metadata
     * @alias module:model/SDTokenMintBulkTokenObjectProps
     * @param mutable {Object} Specifies which properties you want to add (ex. {prop1: 5, prop2: 6, prop3: 7})
     */
    constructor(mutable) { 
        
        SDTokenMintBulkTokenObjectProps.initialize(this, mutable);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, mutable) { 
        obj['mutable'] = mutable;
    }

    /**
     * Constructs a <code>SDTokenMintBulkTokenObjectProps</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SDTokenMintBulkTokenObjectProps} obj Optional instance to populate.
     * @return {module:model/SDTokenMintBulkTokenObjectProps} The populated <code>SDTokenMintBulkTokenObjectProps</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SDTokenMintBulkTokenObjectProps();

            if (data.hasOwnProperty('mutable')) {
                obj['mutable'] = ApiClient.convertToType(data['mutable'], Object);
            }
            if (data.hasOwnProperty('immutable')) {
                obj['immutable'] = ApiClient.convertToType(data['immutable'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SDTokenMintBulkTokenObjectProps</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SDTokenMintBulkTokenObjectProps</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SDTokenMintBulkTokenObjectProps.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

SDTokenMintBulkTokenObjectProps.RequiredProperties = ["mutable"];

/**
 * Specifies which properties you want to add (ex. {prop1: 5, prop2: 6, prop3: 7})
 * @member {Object} mutable
 */
SDTokenMintBulkTokenObjectProps.prototype['mutable'] = undefined;

/**
 * Specifies which properties you want to add (ex. {prop1: 5, prop2: 6, prop3: 7})
 * @member {Object} immutable
 */
SDTokenMintBulkTokenObjectProps.prototype['immutable'] = undefined;






export default SDTokenMintBulkTokenObjectProps;

