/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SDTokenMintBulkTokenObjectProps from './SDTokenMintBulkTokenObjectProps';

/**
 * The SDTokenMintBulkTokenObject model module.
 * @module model/SDTokenMintBulkTokenObject
 * @version 0.0.3
 */
class SDTokenMintBulkTokenObject {
    /**
     * Constructs a new <code>SDTokenMintBulkTokenObject</code>.
     * @alias module:model/SDTokenMintBulkTokenObject
     * @param templateId {Number} Specifies which Template you are creating an instance of (ex. 3)
     * @param amount {String} u64 Number as String, min: 0, max: 9223372036854775807 (ex. \"6\")
     */
    constructor(templateId, amount) { 
        
        SDTokenMintBulkTokenObject.initialize(this, templateId, amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, templateId, amount) { 
        obj['templateId'] = templateId;
        obj['amount'] = amount;
    }

    /**
     * Constructs a <code>SDTokenMintBulkTokenObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SDTokenMintBulkTokenObject} obj Optional instance to populate.
     * @return {module:model/SDTokenMintBulkTokenObject} The populated <code>SDTokenMintBulkTokenObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SDTokenMintBulkTokenObject();

            if (data.hasOwnProperty('templateId')) {
                obj['templateId'] = ApiClient.convertToType(data['templateId'], 'Number');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
            }
            if (data.hasOwnProperty('props')) {
                obj['props'] = SDTokenMintBulkTokenObjectProps.constructFromObject(data['props']);
            }
            if (data.hasOwnProperty('publicMetadata')) {
                obj['publicMetadata'] = ApiClient.convertToType(data['publicMetadata'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SDTokenMintBulkTokenObject</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SDTokenMintBulkTokenObject</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SDTokenMintBulkTokenObject.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['amount'] && !(typeof data['amount'] === 'string' || data['amount'] instanceof String)) {
            throw new Error("Expected the field `amount` to be a primitive type in the JSON string but got " + data['amount']);
        }
        // validate the optional field `props`
        if (data['props']) { // data not null
          SDTokenMintBulkTokenObjectProps.validateJSON(data['props']);
        }

        return true;
    }


}

SDTokenMintBulkTokenObject.RequiredProperties = ["templateId", "amount"];

/**
 * Specifies which Template you are creating an instance of (ex. 3)
 * @member {Number} templateId
 */
SDTokenMintBulkTokenObject.prototype['templateId'] = undefined;

/**
 * u64 Number as String, min: 0, max: 9223372036854775807 (ex. \"6\")
 * @member {String} amount
 */
SDTokenMintBulkTokenObject.prototype['amount'] = undefined;

/**
 * @member {module:model/SDTokenMintBulkTokenObjectProps} props
 */
SDTokenMintBulkTokenObject.prototype['props'] = undefined;

/**
 * Returned to marketplaces as token metadata
 * @member {Object} publicMetadata
 */
SDTokenMintBulkTokenObject.prototype['publicMetadata'] = undefined;






export default SDTokenMintBulkTokenObject;

