/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Error from '../model/Error';
import SDGameGetResponse from '../model/SDGameGetResponse';
import SDGameMutateRequest from '../model/SDGameMutateRequest';

/**
* GameEndpoints service.
* @module api/GameEndpointsApi
* @version 0.0.3
*/
export default class GameEndpointsApi {

    /**
    * Constructs a new GameEndpointsApi. 
    * @alias module:api/GameEndpointsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the gameGetGet operation.
     * @callback module:api/GameEndpointsApi~gameGetGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SDGameGetResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Game
     * Get the Details of Your Game
     * @param {module:api/GameEndpointsApi~gameGetGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SDGameGetResponse}
     */
    gameGetGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SDGameGetResponse;
      return this.apiClient.callApi(
        '/game/get', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameMutatePut operation.
     * @callback module:api/GameEndpointsApi~gameMutatePutCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Mutate Game
     * Change a games data
     * @param {module:model/SDGameMutateRequest} sDGameMutateRequest 
     * @param {module:api/GameEndpointsApi~gameMutatePutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    gameMutatePut(sDGameMutateRequest, callback) {
      let postBody = sDGameMutateRequest;
      // verify the required parameter 'sDGameMutateRequest' is set
      if (sDGameMutateRequest === undefined || sDGameMutateRequest === null) {
        throw new Error("Missing the required parameter 'sDGameMutateRequest' when calling gameMutatePut");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['api_key'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/game/mutate', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
