/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Error from '../model/Error';
import SDHealthResponse from '../model/SDHealthResponse';

/**
* HealthEndpoints service.
* @module api/HealthEndpointsApi
* @version 0.0.3
*/
export default class HealthEndpointsApi {

    /**
    * Constructs a new HealthEndpointsApi. 
    * @alias module:api/HealthEndpointsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the healthGet operation.
     * @callback module:api/HealthEndpointsApi~healthGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SDHealthResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Health
     * Get system health info
     * @param {module:api/HealthEndpointsApi~healthGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SDHealthResponse}
     */
    healthGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SDHealthResponse;
      return this.apiClient.callApi(
        '/health', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
