/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StardustCoreSdk);
  }
}(this, function(expect, StardustCoreSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StardustCoreSdk.TemplateEndpointsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TemplateEndpointsApi', function() {
    describe('templateCountGet', function() {
      it('should call templateCountGet successfully', function(done) {
        //uncomment below and update the code to test templateCountGet
        //instance.templateCountGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateCreatePost', function() {
      it('should call templateCreatePost successfully', function(done) {
        //uncomment below and update the code to test templateCreatePost
        //instance.templateCreatePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateGetAllGet', function() {
      it('should call templateGetAllGet successfully', function(done) {
        //uncomment below and update the code to test templateGetAllGet
        //instance.templateGetAllGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateGetGet', function() {
      it('should call templateGetGet successfully', function(done) {
        //uncomment below and update the code to test templateGetGet
        //instance.templateGetGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateGetTokensGet', function() {
      it('should call templateGetTokensGet successfully', function(done) {
        //uncomment below and update the code to test templateGetTokensGet
        //instance.templateGetTokensGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateMutatePut', function() {
      it('should call templateMutatePut successfully', function(done) {
        //uncomment below and update the code to test templateMutatePut
        //instance.templateMutatePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templatePropsRemoveDelete', function() {
      it('should call templatePropsRemoveDelete successfully', function(done) {
        //uncomment below and update the code to test templatePropsRemoveDelete
        //instance.templatePropsRemoveDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateRemoveDelete', function() {
      it('should call templateRemoveDelete successfully', function(done) {
        //uncomment below and update the code to test templateRemoveDelete
        //instance.templateRemoveDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
