/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StardustCoreSdk);
  }
}(this, function(expect, StardustCoreSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StardustCoreSdk.TokenEndpointsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TokenEndpointsApi', function() {
    describe('tokenBurnPost', function() {
      it('should call tokenBurnPost successfully', function(done) {
        //uncomment below and update the code to test tokenBurnPost
        //instance.tokenBurnPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tokenGetGet', function() {
      it('should call tokenGetGet successfully', function(done) {
        //uncomment below and update the code to test tokenGetGet
        //instance.tokenGetGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tokenMintBulkPost', function() {
      it('should call tokenMintBulkPost successfully', function(done) {
        //uncomment below and update the code to test tokenMintBulkPost
        //instance.tokenMintBulkPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tokenMutatePut', function() {
      it('should call tokenMutatePut successfully', function(done) {
        //uncomment below and update the code to test tokenMutatePut
        //instance.tokenMutatePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tokenPropsRemoveDelete', function() {
      it('should call tokenPropsRemoveDelete successfully', function(done) {
        //uncomment below and update the code to test tokenPropsRemoveDelete
        //instance.tokenPropsRemoveDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tokenTransferPost', function() {
      it('should call tokenTransferPost successfully', function(done) {
        //uncomment below and update the code to test tokenTransferPost
        //instance.tokenTransferPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tokenWithdrawPost', function() {
      it('should call tokenWithdrawPost successfully', function(done) {
        //uncomment below and update the code to test tokenWithdrawPost
        //instance.tokenWithdrawPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
